### ISSUE TITLE
Connecting over USB

### ISSUE THREAD

**Issue by AngusEason** [geissdoerfer/python-spd3303x#2]
Hi there,
I am trying to use this library to read voltage and current information over USB. However, when I run it I get the following error:
```
Trying to auto-detect USB device
Traceback (most recent call last):
  File "c:\Users\AngusEason\Desktop\Programming power supply\SPD3303X.py", line 9, in <module>
    with SPD3303X.usb_device() as dev:
  File "C:\Users\AngusEason\AppData\Local\Programs\Python\Python310\lib\site-packages\spd3303x\__init__.py", line 106, in __enter__
    raise Exception("No device found")
Exception: No device found
```
I believe it is a driver issue where I do not have all the required prerequisites. What drivers, versions, or other software is required to be installed for this to work?

**Comment by AngusEason** [comment]
Found the issue. In the __enter__ function when it attempts to auto-detect the USB device it looks for `'SPD3XID'` in the resources list. However, for my system the address was `'USB0::0xF4EC::0x1430::SPD3XJFQ6R5257::INSTR'`. Changing it to search for `'SPD3X'` solved the issue.

```
    def __enter__(self):
        rm = pyvisa.ResourceManager("@py")
        if self._visa_rscr is None:
            logger.debug("Trying to auto-detect USB device")
            resources = rm.list_resources()
            for res_str in resources:
                if "SPD3XID" in res_str:
                    self._visa_rscr = res_str
            if self._visa_rscr is None:
                raise Exception("No device found")
```

**Comment by geissdoerfer** [comment]
Thanks for reporting. Could you please check if the code I just pushed to the `fix_specificer` branch works for your device?

**Comment by AngusEason** [comment]
That code does not fix it, however if you just remove the "any" it does. e.g. 
`if (dev_spec in res_str for dev_spec in ["SPD3XID", "SPD3ID"]):`

**Comment by geissdoerfer** [comment]
Oh, I just noticed that I had apparently misread your resource specifier. I fixed it on the `fix_specifier` branch, using the solution you suggested in your second comment. This should work for both device types. Please try again.

> That code does not fix it, however if you just remove the "any" it does. e.g. `if (dev_spec in res_str for dev_spec in ["SPD3XID", "SPD3ID"]):`

That's not a good idea because it will always evaluate True no matter what's in res_str.

**Comment by geissdoerfer** [comment]
Hi @AngusEason, could you help me and quickly check if the code on the `fix_specifier` branch works with your device?

**Comment by Heftie** [comment]
i did not work correctly for me (branch fix_specifier). Seams that the issue comes from pyvisa or the "@py". Below I have my debugged code snippets: and the console log output.

```
def __enter__(self):
        rm = pyvisa.ResourceManager("@py")
        if self._visa_rscr is None:
            logger.debug("Trying to auto-detect USB device")
            resources = rm.list_resources()
            logger.debug(resources)
            for res_str in resources:
                if "SPD3X" in res_str:
                    self._visa_rscr = res_str
```
Trying to auto-detect USB device
('ASRL3::INSTR',)

```
def __enter__(self):
        rm = pyvisa.ResourceManager()
        if self._visa_rscr is None:
            logger.debug("Trying to auto-detect USB device")
            resources = rm.list_resources()
            logger.debug(resources)
            for res_str in resources:
                if "SPD3X" in res_str:
                    self._visa_rscr = res_str
```
Trying to auto-detect USB device
('USB0::0xF4EC::0x1430::SPD3XJFC7R0760::INSTR', 'ASRL3::INSTR')

The SP3X change does work for me in that way. I would suggest to remove the "@py" from the pyvisa.ResourceManager.

**Comment by geissdoerfer** [comment]
OK thanks for checking. I won't have access to the device in the foreseeable future so can't test your suggestions.
